import fs from 'node:fs/promises';
import path from 'node:path';
import { randomUUID } from 'node:crypto';
import type { ProviderId, AgentSendOptions, OperationReceipt } from './interop.js';
import type { InteropRegistry } from './interop-runtime.js';

export interface ConversationParticipant { id: string; provider: ProviderId; nativeId: string; workspaceId?: string; role?: 'sender' | 'reviewer' | 'editor'; }
export interface ConversationMessage { id: string; conversationId: string; sender: string; recipient: string; text: string; replyTo?: string; createdAt: string; receipt?: OperationReceipt; }
export interface Conversation { id: string; title: string; participants: ConversationParticipant[]; messages: ConversationMessage[]; createdAt: string; updatedAt: string; }
const clone = <T>(value: T): T => JSON.parse(JSON.stringify(value)) as T;
const stamp = () => new Date().toISOString();
const newId = (prefix: string) => `${prefix}_${randomUUID()}`;

export class ConversationStore {
  private conversations = new Map<string, Conversation>();
  constructor(private readonly file: string) {}
  async load(): Promise<void> { try { const raw = JSON.parse(await fs.readFile(this.file, 'utf8')) as { conversations?: unknown[] }; for (const value of raw.conversations ?? []) { const conversation = value as Conversation; if (conversation?.id && Array.isArray(conversation.participants) && Array.isArray(conversation.messages)) this.conversations.set(conversation.id, conversation); } } catch (error) { if ((error as NodeJS.ErrnoException).code !== 'ENOENT') throw new Error(`Conversation state is not readable: ${error instanceof Error ? error.message : String(error)}`); } }
  list(): Conversation[] { return [...this.conversations.values()].sort((a, b) => b.updatedAt.localeCompare(a.updatedAt)).map(clone); }
  get(id: string): Conversation | null { return clone(this.conversations.get(id) ?? null); }
  async create(title: string): Promise<Conversation> { const time = stamp(); const conversation: Conversation = { id: newId('conversation'), title: title.trim().slice(0, 300), participants: [], messages: [], createdAt: time, updatedAt: time }; this.conversations.set(conversation.id, conversation); await this.save(); return clone(conversation); }
  async join(conversationId: string, participant: Omit<ConversationParticipant, 'id'> & { id?: string }): Promise<Conversation> { const conversation = this.require(conversationId); const existing = conversation.participants.find((value) => value.provider === participant.provider && value.nativeId === participant.nativeId); if (!existing) conversation.participants.push({ ...participant, id: participant.id ?? `${participant.provider}:${participant.nativeId}` }); conversation.updatedAt = stamp(); await this.save(); return clone(conversation); }
  async send(conversationId: string, sender: string, recipient: string, text: string, registry: InteropRegistry, options?: AgentSendOptions, replyTo?: string): Promise<{ message: ConversationMessage; receipt: OperationReceipt }> { const conversation = this.require(conversationId); if (!conversation.participants.some((value) => value.id === sender)) throw new Error(`Unknown conversation sender ${sender}`); const destination = conversation.participants.find((value) => value.id === recipient); if (!destination) throw new Error(`Unknown conversation recipient ${recipient}`); const message: ConversationMessage = { id: newId('message'), conversationId, sender, recipient, text: text.trim(), ...(replyTo ? { replyTo } : {}), createdAt: stamp() }; conversation.messages.push(message); if (conversation.messages.length > 500) conversation.messages.splice(0, conversation.messages.length - 500); const envelope = `[agent-interop message ${message.id} from ${sender}]\n${message.text}`; const receipt = await registry.send(destination.provider, destination.nativeId, envelope, 'send', options); message.receipt = receipt; conversation.updatedAt = stamp(); await this.save(); return { message: clone(message), receipt: clone(receipt) }; }
  async read(conversationId: string, after = 0, limit = 100): Promise<{ conversation: Conversation; next: number }> { const conversation = this.require(conversationId); const messages = conversation.messages.slice(after, after + Math.min(Math.max(limit, 1), 100)); return { conversation: { ...clone(conversation), messages }, next: after + messages.length }; }
  private require(id: string): Conversation { const conversation = this.conversations.get(id); if (!conversation) throw new Error(`Unknown conversation ${id}`); return conversation; }
  private async save(): Promise<void> { await fs.mkdir(path.dirname(this.file), { recursive: true, mode: 0o700 }); const lock = `${this.file}.lock`; let handle; for (let i = 0; i < 100; i++) { try { handle = await fs.open(lock, 'wx'); break; } catch (error) { if ((error as NodeJS.ErrnoException).code !== 'EEXIST') throw error; await new Promise((resolve) => setTimeout(resolve, 10)); } } if (!handle) throw new Error('Could not acquire conversation state lock'); try { const temp = `${this.file}.${randomUUID()}.tmp`; await fs.writeFile(temp, JSON.stringify({ conversations: [...this.conversations.values()] }, null, 2), { encoding: 'utf8', mode: 0o600 }); await fs.rename(temp, this.file); if (process.platform !== 'win32') await fs.chmod(this.file, 0o600); } finally { await handle.close(); await fs.unlink(lock).catch(() => undefined); } }
}
