import type { Json } from './types.js';
import type { AgentAdapter, AgentCapabilities, AgentEvent, AgentSession, OperationReceipt, AgentSendOptions } from './interop.js';
import type { Runtime } from './runtime.js';
import { VERSION } from './version.js';

export class FreebuffAdapter implements AgentAdapter {
  readonly id = 'freebuff' as const;
  constructor(private readonly runtime: Runtime) {}
  async capabilities(): Promise<AgentCapabilities> { const legacy = await this.runtime.capabilities(); const c = legacy as any; const available = Boolean(c.orchestrator || c.product === 'cli'); const write = !c.readOnly; const record = (supported: boolean, reason?: string) => ({ supported, state: supported ? 'available' as const : 'degraded' as const, transport: c.product === 'cli' ? 'managed PTY' : 'http', protocol: 'Freebuff native bridge', reason }); return { provider: this.id, adapterVersion: VERSION, providerVersion: c.version, authorization: write ? 'authorized' : available ? 'unknown' : 'unauthorized', discovery: record(available, available ? undefined : 'Freebuff was not discovered'), sessions: record(available), sendMessage: record(write, c.readOnly ? 'Read only mode or PTY startup failed' : undefined), steer: record(false, 'Freebuff exposes message send but not a separate steer contract'), cancel: record(write), events: record(available), diff: record(false, 'Native diff route is not exposed by the current bridge'), permissions: record(false, 'Permission response route is not exposed by the current bridge'), model: record(write), reasoning: record(write), limitations: ['Desktop writes require the verified launch ID handshake', 'CLI writes require a successful PTY startup probe', 'The adapter preserves the existing Freebuff bridge behavior'] }; }
  async listSessions(): Promise<AgentSession[]> { const threads = await this.runtime.listThreads(); return threads.map((t) => ({ ...t, id: `freebuff:${t.id}`, nativeId: t.id, provider: this.id, transport: 'native bridge', provenance: { discoveredAt: new Date().toISOString(), source: 'Freebuff runtime', native: true } })); }
  async getSession(nativeId: string): Promise<AgentSession | null> { nativeId = normalizeFreebuffId(nativeId); const t = await this.runtime.getThread(nativeId); return { ...t, id: `freebuff:${nativeId}`, nativeId, provider: this.id, transport: 'native bridge', provenance: { discoveredAt: new Date().toISOString(), source: 'Freebuff runtime', native: true } }; }
  async resumeSession(nativeId: string): Promise<AgentSession> { nativeId = normalizeFreebuffId(nativeId); await this.runtime.resume(nativeId); const session = await this.getSession(nativeId); if (!session) throw new Error(`Freebuff session ${nativeId} was not found`); return session; }
  async *events(nativeId: string): AsyncIterable<AgentEvent> { nativeId = normalizeFreebuffId(nativeId); let cursor = 0; for (let attempt = 0; attempt < 20; attempt += 1) { const snapshot = await this.runtime.watchThread(nativeId, cursor, 1500, 50); for (const event of snapshot.events) { cursor = Math.max(cursor, event.sequence); const data = event.raw ?? JSON.parse(JSON.stringify({ state: event.state, text: event.text, files: event.files, error: event.error })); yield { provider: this.id, nativeId, sequence: event.sequence, timestamp: event.timestamp, type: event.kind, data }; } if (!snapshot.connected && snapshot.stale) return; } }
  async send(nativeId: string, text: string, options?: AgentSendOptions): Promise<OperationReceipt> { nativeId = normalizeFreebuffId(nativeId); if (options?.agent) throw new Error('Freebuff does not expose a separate agent control'); if (options?.model) await this.runtime.setModel(nativeId, options.model.modelID); if (options?.reasoning) await this.runtime.setReasoning(nativeId, options.reasoning); const detail = await this.runtime.sendMessage(nativeId, text); return { provider: this.id, nativeId, operation: 'send', accepted: true, status: 'queued', detail }; }
  async cancel(nativeId: string): Promise<OperationReceipt> { nativeId = normalizeFreebuffId(nativeId); return { provider: this.id, nativeId, operation: 'cancel', accepted: true, detail: await this.runtime.stop(nativeId) }; }
  async setModel(nativeId: string, model: string): Promise<OperationReceipt> { nativeId = normalizeFreebuffId(nativeId); return { provider: this.id, nativeId, operation: 'set_model', accepted: true, status: 'completed', detail: await this.runtime.setModel(nativeId, model) }; }
  async setReasoning(nativeId: string, effort: string): Promise<OperationReceipt> { nativeId = normalizeFreebuffId(nativeId); return { provider: this.id, nativeId, operation: 'set_reasoning', accepted: true, detail: await this.runtime.setReasoning(nativeId, effort) }; }
}

export function normalizeFreebuffId(id: string): string { return id.startsWith('freebuff:') ? id.slice('freebuff:'.length) : id; }
