import type { Json } from './types.js';
import { randomUUID } from 'node:crypto';
import type { AgentAdapter, AgentCapabilities, AgentEvent, AgentSession, EvidenceRecord, OperationReceipt, ProviderId, WorkGraphSnapshot, AgentSendOptions, ModelSelection } from './interop.js';

export class InteropRegistry {
  private adapters = new Map<ProviderId, AgentAdapter>();
  private sessionErrors: Array<{ provider: ProviderId; error: string }> = [];
  private evidence: EvidenceRecord[] = [];
  register(adapter: AgentAdapter) { this.adapters.set(adapter.id, adapter); return this; }
  listProviders(): ProviderId[] { return [...this.adapters.keys()]; }
  adapter(provider: ProviderId) { const value = this.adapters.get(provider); if (!value) throw new Error(`Unknown provider ${provider}`); return value; }
  async capabilities(): Promise<AgentCapabilities[]> { return Promise.all([...this.adapters.values()].map((a) => a.capabilities())); }
  async listSessions(provider?: ProviderId): Promise<AgentSession[]> { this.sessionErrors = []; const adapters = provider ? [this.adapter(provider)] : [...this.adapters.values()]; const results = await Promise.all(adapters.map(async (adapter) => { try { return await adapter.listSessions(); } catch (error) { this.sessionErrors.push({ provider: adapter.id, error: error instanceof Error ? error.message : String(error) }); return []; } })); const sessions = results.flat(); for (const s of sessions) this.capture({ id: `${s.provider}:${s.nativeId}`, provider: s.provider, nativeId: s.nativeId, kind: 'session', capturedAt: new Date().toISOString(), trust: 'native', summary: s.title ?? 'Native session discovered', data: s as unknown as Json }); return sessions; }
  getSessionErrors(): Array<{ provider: ProviderId; error: string }> { return [...this.sessionErrors]; }
  async send(provider: ProviderId, nativeId: string, text: string, mode: 'send' | 'steer' = 'send', options?: AgentSendOptions): Promise<OperationReceipt> { const adapter = this.adapter(provider); const fn = mode === 'steer' ? adapter.steer : adapter.send; if (!fn) throw new Error(`${provider} does not support ${mode}`); const result = await fn.call(adapter, nativeId, text, options); this.capture({ id: `${Date.now()}-${randomUUID()}`, provider, nativeId, kind: 'event', capturedAt: new Date().toISOString(), trust: 'observed', summary: `${mode} ${result.status ?? (result.accepted ? 'accepted' : 'rejected')}`, data: result.detail ?? null }); return result; }
  async cancel(provider: ProviderId, nativeId: string): Promise<OperationReceipt> { const fn = this.adapter(provider).cancel; if (!fn) throw new Error(`${provider} does not support cancel`); return fn.call(this.adapter(provider), nativeId); }
  async create(provider: ProviderId, options: { cwd?: string; title?: string }): Promise<AgentSession> { const fn = this.adapter(provider).createSession; if (!fn) throw new Error(`${provider} does not support session creation`); return fn.call(this.adapter(provider), options); }
  async resume(provider: ProviderId, nativeId: string): Promise<AgentSession> { const adapter = this.adapter(provider); const session = adapter.resumeSession ? await adapter.resumeSession(nativeId) : await adapter.getSession(nativeId); if (!session) throw new Error(`${provider} could not resume ${nativeId}`); return session; }
  async permission(provider: ProviderId, nativeId: string, requestId: string, decision: string): Promise<OperationReceipt> { const fn = this.adapter(provider).respondPermission; if (!fn) throw new Error(`${provider} does not support permission responses`); return fn.call(this.adapter(provider), nativeId, requestId, decision); }
  async model(provider: ProviderId, nativeId: string, model: ModelSelection): Promise<OperationReceipt> { const fn = this.adapter(provider).setModel; if (!fn) throw new Error(`${provider} does not support model changes`); return fn.call(this.adapter(provider), nativeId, model); }
  async reasoning(provider: ProviderId, nativeId: string, effort: string): Promise<OperationReceipt> { const fn = this.adapter(provider).setReasoning; if (!fn) throw new Error(`${provider} does not support reasoning changes`); return fn.call(this.adapter(provider), nativeId, effort); }
  async diff(provider: ProviderId, nativeId: string): Promise<Json | null> { const fn = this.adapter(provider).getDiff; if (!fn) throw new Error(`${provider} does not expose native diff`); const result = await fn.call(this.adapter(provider), nativeId); this.capture({ id: `${Date.now()}-${randomUUID()}`, provider, nativeId, kind: 'diff', capturedAt: new Date().toISOString(), trust: 'native', summary: 'Native diff read', data: result ?? null }); return result; }
  async readEvents(provider: ProviderId, nativeId: string, limit = 50): Promise<AgentEvent[]> { const fn = this.adapter(provider).events; if (!fn) throw new Error(`${provider} does not expose native events`); const events: AgentEvent[] = []; for await (const event of fn.call(this.adapter(provider), nativeId)) { events.push(event); if (events.length >= limit) break; } return events; }
  capture(record: EvidenceRecord) { this.evidence.push(record); if (this.evidence.length > 1000) this.evidence.splice(0, this.evidence.length - 1000); }
  async graph(): Promise<WorkGraphSnapshot> { return { sessions: await this.listSessions(), edges: this.evidence.map((e) => ({ from: `${e.provider}:${e.nativeId}`, to: e.id, kind: 'evidence' as const })), evidence: [...this.evidence] }; }
  dispose() { for (const adapter of this.adapters.values()) adapter.dispose?.(); }
}
